# ================== Spring Boot App ==================
spring.application.name=online-banking-backend


# ================== MySQL Database ==================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080



# ================== Driver ==================


# ================== JPA ==================


spring.jpa.show-sql=true

# ================== Gmail SMTP ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================== Fast2SMS ==================
fast2sms.api.key=${FAST2SMS_API_KEY}
