# ================== Spring Boot App ==================
spring.application.name=online-banking-backend
server.port=${PORT:8080}

# ================== MySQL Database ==================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ================== Driver ==================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ================== JPA ==================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================== Gmail SMTP ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================== Fast2SMS ==================
fast2sms.api.key=${FAST2SMS_API_KEY}
