# ================== Spring Boot App ==================
spring.application.name=online-banking-backend


# ================== MySQL Database ==================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-24837f40-sahamina5586-4e7f.i.aivencloud.com:18059/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yourpassword}

spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

# ================== Driver ==================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================== JPA ==================


spring.jpa.show-sql=true

# ================== Gmail SMTP ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================== Fast2SMS ==================
fast2sms.api.key=${FAST2SMS_API_KEY}
